### ISSUE TITLE
GCC 4.3 breaks dependencies

### ISSUE THREAD

**Issue by GoogleCodeExporter** [erincatto/box2d#87]
```
What steps will reproduce the problem?
1. Compile with GCC 4.3 and higher

What is the expected output? What do you see instead?
Expected is a complete compile, instead it breaks on:
Dynamics/Contacts/b2PolyContact.cpp: In member function ‘virtual void
b2PolygonContact::Evaluate(b2ContactListener*)’:
Dynamics/Contacts/b2PolyContact.cpp:54: error: ‘memcpy’ was not declared in
this scope
Fixing this gives the same error in the next file(s).

What version of the product are you using? On what operating system?
-Ubuntu 9.10
-gcc (Ubuntu 4.4.1-4ubuntu9) 4.4.1
-Box2D_v2.0.1

Please provide any additional information below.
Please take a look at
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=455286, the committer of
that bug explains why this occurs. 
Resolution is adding '#include <cstring>' to all files using memcpy

```

Original issue reported on code.google.com by `aro...@gmail.com` on 16 Feb 2010 at 4:53
